### ISSUE TITLE
项目安装了expose-loader和jquery并且在webpack.config.js中做了配置还是报错：jQuery is not defined

### ISSUE THREAD

**Issue by dxiuxiu** [arixse/ztree-for-react#4]
使用webpack2.x,安装了"jquery": "^3.3.1"和"expose-loader": "^0.7.5"，在webpack.config.js中做了相关配置如下，module: {
    loaders: [
      {
        test: /\.js?$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'es2015'],
          plugins: ['react-html-attrs'], //添加组件的插件配置
        }
      },
      {
        // 得到jquery模块的绝对路径
        test: require.resolve('jquery'),
        // 将jquery绑定为window.jQuery 和 window.$
        loader: 'expose-loader?jQuery!expose-loader?$'
    }

    ]
  },

以上是我已做过的所有操作，看起来似乎没有什么问题了但是仍然报错jQuery没有定义

**Comment by arixse** [comment]
把jQuery的版本换成2.2.1的试试

**Comment by dxiuxiu** [comment]
你好，按照你说的换成jQuery2.2.1之后jQuery未定义的错误解决了，但是执行还是报错，错误信息如下：

ztree-for-react.js:56 Uncaught TypeError: Cannot read property 'init' of undefined
 at ReactZtree.renderZtreeDom (ztree-for-react.js:56)

我用的就是提供的测试代码稍微修改了一下，我的代码如下：
import React,{Component} from 'react';
import $ from 'jquery';
import ReactZtree from 'ztree-for-react';

// import React, { Component } from 'react';
// import ReactZtree from '../lib/ztree-for-react';
const nodes= [
	{name: '父节点1',
    id:0,
     children: [
		{name: '子节点1',
    id:1},
		{name: '子节点2',id:2,children:[
      {name:'子节点3',id:3}
    ]}
	]}
];
const check={
  enable:true
}
export default class App extends Component {
  render() {
    return (
      <div>
        <ReactZtree nodes={nodes} events={this.getEvents()} check={check} ref="ztree"/>
      </div>
    );
  }
  getEvents(){
    return {
      'onClick':(event,treeId,treeNode)=>{this.handleClick(event,treeId,treeNode)},
      'onCheck':(event,treeId,treeNode)=>{this.handleClick(event,treeId,treeNode)}
    }
  }
  handleClick(event,treeId,treeNode){
    console.log(treeNode);
    console.log(this.refs.ztree.ztreeObj.getCheckedNodes());
  }
  handleCheck(event,treeId,treeNode){
    console.log(treeNode);
  }
}

**Comment by arixse** [comment]
ztree-for-react 依赖jQuery和ztree，所以要把两个都import进去，你忘了加 import 'ztree'

**Comment by dxiuxiu** [comment]
谢谢你，问题已解决
