### ISSUE TITLE
ztree-for-react组件移除时报错 Uncaught TypeError: this.ztreeObj.destory is not a function

### ISSUE THREAD

**Issue by dxiuxiu** [arixse/ztree-for-react#5]
你好，我在使用ztree-for-react时发现在移除组件时会报错：ztree-for-react组件移除时报错Uncaught TypeError: this.ztreeObj.destory is not a function
    at eval (eval at componentWillUnmount (ztree-for-react.js:51), <anonymous>:1:15)
控制台信息：
this.ztreeObj.destory();
VM4502:1 Uncaught TypeError: this.ztreeObj.destory is not a function
    at eval (eval at componentWillUnmount (ztree-for-react.js:51), <anonymous>:1:15).......
此时控制台测试执行时发现expandAll()和getNodes()不会报错，如下
this.ztreeObj.expandAll()
false
this.ztreeObj.getNodes();
[{…}]
然后查看this.ztreeObj发现里面也是有destory的

**Comment by arixse** [comment]
不好意思，里面的destroy方法名称写错了

**Comment by dxiuxiu** [comment]
哦哦，已经更新了吗？我现在直接cnpm可以下载到更新后的版本吗？
